### ISSUE TITLE
Restarting Bridges with --force causes networking to stop

### ISSUE THREAD

**Issue by djh00t** [mrlesmithjr/ansible-config-interfaces#13]
Hi Guys,

I'm testing this role on Ubuntu 16.04 and have found that using `--force` when restarting bridges with slaved interfaces causes networking to fail, especially bad if you're sshing into the box using the bridge.

The good news (I think) is that it looks like removing `--force` seems to make things work as expected. Is there a specific reason you're using force for this command?

**Comment by mrlesmithjr** [comment]
@djh00t Thanks for the feedback. It's been a while since I have done anything with this, but the `--force` was added when specifically dealing with certain scenarios around KVM/Docker/MAAS if I recall. At that time, there were bridges/slaves/Quagga and etc. which would cause an interface to not properly reset. With that being said, it might be worthwhile to look into this again. Or possibly add an option to not force by default, but add the ability to do so if needed.

**Comment by djh00t** [comment]
After picking through this a bunch more overnight I've found that the issue I was experiencing was actually caused by ifup trying to run too soon after ifdown. Adding a "sleep 3" between commands has provided a smoother solution.

That said it would be nice not to force by default. I will have a play with the stuff I've done overnight and submit a PR. Not sure I'll get headspace to add the optional force however.

**Comment by mrlesmithjr** [comment]
Sounds great. Thanks again for the feedback.
